{application,tcp_chat,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{tcp_chat_app,[]}},
              {applications,[kernel,stdlib,lager]},
              {env,[]},
              {modules,[client,room,tcp_chat_app,tcp_chat_sup]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
